name: CI Pipeline 
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
      - name:  Setup node 
        uses: actions/setup-node@v4
        with:
          node-version: 22 
      - name: Install Backend Dependencies 
        run: | 
            cd backend 
            npm install 
      - name: Install Frontend Dependencies
        run: | 
            cd frontend 
            npm install 
      - name: Build Backend Docker Image 
        run : | 
              docker build -t devops-backend ./backend 
      - name: Build Frontend Docker Image 
        run: | 
              docker build -t devops-frontend ./frontend  



          
      

    